import Title from "@/components/home-page/header/title";
import Footer from "@/components/ui/footer";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Title />
          {children}
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
